#!/bin/bash
# ---------------------------------------------------------------------------
# disable - Removes configuration symlinks for a single domain or a domain and all its subdomains

# Copyright (c) 2015, FujiMakoto <makoto@makoto.io>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated 
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of 
# the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE 
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS 
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR 
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Usage: disable domain [section]

# Latest revision:
# 2015-12-26  Initial commit (v0.1)
# ---------------------------------------------------------------------------

readonly NGINX_BASEDIR="/etc/nginx";

# Set arguments
DOMAIN=$1;
SECTION=$2;

if [ $# -eq 0 ]; then
	echo "Please provide at least the domain of the server you wish to disable";
	echo "(Example: /etc/nginx/scripts/disable example.org subdomain)";
	exit 1;
fi

# Disable all under a domain?
if [ $# -eq 1 ]; then
	rm -fv "${NGINX_BASEDIR}/sites-enabled/*${DOMAIN}";
	rm -fv "${NGINX_BASEDIR}/sites-enabled/${DOMAIN}";
	exit 0;
fi

# Disable a single domain section
if [ $SECTION = 'root' ]; then
	rm -v "${NGINX_BASEDIR}/sites-enabled/${DOMAIN}";
else
	rm -v "${NGINX_BASEDIR}/sites-enabled/${SECTION}.${DOMAIN}";
fi
